# Generated by Django 2.1.1 on 2018-09-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('Person', 'Person'), ('Email Group Distro', 'Group'), ('API Endpoint', 'API')], max_length=30, null=True),
        ),
    ]
