# Generated by Django 2.1.1 on 2018-11-01 05:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbaas', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("create or replace view application_contacts_details_view as "
                          "  select a.id, c.id as contact_id, "
                          "  a.application_name, c.contact_name, c.contact_type, c.contact_phone, c.contact_email, c.active_sw "
                          "  from application_contact ac, application a, contact c "
                          "  where ac.application_id = a.id "
                          "  and ac.contact_id = c.id "
                          "  and ac.active_sw = TRUE",
                          "drop view application_contacts_details_view", ),
    ]
