# Generated by Django 2.1.4 on 2018-12-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetricsMountPoint',
            new_name='Metrics_MountPoint',
        ),
        migrations.RenameField(
            model_name='issuetracker',
            old_name='prior_status',
            new_name='pending_status',
        ),
    ]
