# Generated by Django 2.1.4 on 2018-12-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolserver',
            name='datacenter',
        ),
        migrations.RemoveField(
            model_name='poolserver',
            name='environment',
        ),
        migrations.AlterField(
            model_name='server',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='dbaas.Cluster'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbaas.Datacenter'),
        ),
        migrations.AlterField(
            model_name='server',
            name='db_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='db_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbaas.Environment'),
        ),
        migrations.AlterField(
            model_name='server',
            name='metrics_sw',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='node_role',
            field=models.CharField(choices=[('Primary', 'Primary Node'), ('SecondarySync', 'Secondary Node - Replication is Synchronous'), ('SecondaryAsync', 'Secondary Node- Replication is Asynchronous'), ('Arbiter', 'Arbiter Node'), ('PoolServer', 'PoolServer'), ('PoolServerLocked', 'PoolServerLocked')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ram_gb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_health',
            field=models.CharField(blank=True, choices=[('ServerConfig', 'Server Configuring'), ('ServerUp', 'Server Up and Healthy'), ('ServerUpWithIssues', 'Server is Up but something is Not Healthy'), ('ServerDown', 'Server is Down'), ('ServerOnLineMaint', 'Server On-Line Maintenance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_ip',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.DeleteModel(
            name='PoolServer',
        ),
    ]
