# Generated by Django 2.1.1 on 2018-11-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
        migrations.AlterModelTable(
            name='alert',
            table='alert',
        ),
    ]
