# Generated by Django 2.1.4 on 2018-12-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0002_auto_20181230_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='requested_cpu',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='requested_db_gb',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='requested_ram_gb',
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup_size_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup_status',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Failed', 'Failed'), ('Successful', 'Successful')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='db_size_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='deleted_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='stop_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='exp_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clusternote',
            name='note',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='clusternote',
            name='note_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clusternote',
            name='ticket',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='restore',
            name='restore_status',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Failed', 'Failed'), ('Successful', 'Successful')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='restore',
            name='restore_to_dttm',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='restore',
            name='stop_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restore',
            name='ticket',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='serveractivity',
            name='start_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serveractivity',
            name='stop_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
