# Generated by Django 2.1.1 on 2018-11-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0003_auto_20181111_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationContactsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=60)),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_type', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(default='default@email.com', max_length=254)),
                ('active_sw', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'application_contacts_view',
                'managed': False,
            },
        ),
    ]
