# Generated by Django 2.1.4 on 2018-12-31 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0004_server_last_reboot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacenter',
            options={'ordering': ['order_num']},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['order_num']},
        ),
        migrations.RenameField(
            model_name='environment',
            old_name='order',
            new_name='order_num',
        ),
        migrations.AddField(
            model_name='datacenter',
            name='order_num',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='datacenter',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='env_name',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='datacenter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='datacenter',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='datacenter',
            name='order',
        ),
    ]
