# Generated by Django 2.1.1 on 2018-11-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0004_applicationcontactsview'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Blackout', 'Blackout'), ('Normal', 'Normal'), ('Unknown', 'Unknown')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='serveractivity',
            name='activity_status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('PendingRestart', 'PendingRestart'), ('Processing', 'Processing'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Queued', max_length=15),
        ),
    ]
