# Generated by Django 2.1.1 on 2018-09-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0004_auto_20180925_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='health',
        ),
        migrations.AddField(
            model_name='cluster',
            name='cluster_health',
            field=models.CharField(choices=[('ClusterConfig', 'Cluster Configuring'), ('ClusterUp', 'Nodes Up and Healthy'), ('ClusterUpWithIssues', 'Primary is Up but something is Not Healthy'), ('ClusterDown', 'Cluster is Down'), ('ClusterOnLineMaint', 'On-Line Maintenance')], default='ClusterConfig', max_length=30),
        ),
    ]
