# Generated by Django 2.1.1 on 2018-11-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0005_auto_20181112_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsCPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('cpu_idle_pct', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cpu_user_pct', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cpu_system_pct', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cpu_wait_pct', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cpu_steal_pct', models.DecimalField(decimal_places=1, max_digits=3)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_cpu',
            },
        ),
        migrations.CreateModel(
            name='MetricsDbPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('db_ping_status', models.CharField(default='', max_length=30)),
                ('db_ping_response_ms', models.IntegerField(default=0)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_db_ping',
            },
        ),
        migrations.CreateModel(
            name='MetricsLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('load_1min', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('load_5min', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('load_15min', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_load',
            },
        ),
        migrations.CreateModel(
            name='MetricsMountPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('mount_point', models.CharField(default='', max_length=30)),
                ('allocated_gb', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('used_gb', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('used_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_mountpoint',
            },
        ),
    ]
