# Generated by Django 2.1.4 on 2019-01-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0005_auto_20181230_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='dbms_type',
            field=models.CharField(blank=True, choices=[('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB')], max_length=20, null=True),
        ),
    ]
