# Generated by Django 2.1.1 on 2018-11-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0006_metricscpu_metricsdbping_metricsload_metricsmountpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricscpu',
            name='cpu_guest_nicemak_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='metricscpu',
            name='cpu_guest_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='metricscpu',
            name='cpu_irq_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='metricscpu',
            name='cpu_idle_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='metricscpu',
            name='cpu_iowait_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='metricscpu',
            name='cpu_steal_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='metricscpu',
            name='cpu_system_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='metricscpu',
            name='cpu_user_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
