# Generated by Django 2.1.1 on 2018-11-24 06:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0007_auto_20181121_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Blackout', 'Blackout'), ('Normal', 'Normal'), ('Unknown', 'Unknown')], default='', max_length=15)),
                ('alert_dttm', models.DateTimeField(auto_now_add=True)),
                ('sent_notification_sw', models.BooleanField(default=False)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_detail',
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_dttm', models.DateTimeField(auto_now_add=True)),
                ('alert_note', models.CharField(default='', max_length=10000)),
                ('acknowledged_by', models.CharField(default='', max_length=30)),
                ('acknowledged_dttm', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc))),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('alert_detail', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.AlertDetail')),
                ('application_contact', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.ApplicationContact')),
            ],
            options={
                'db_table': 'alert_notification',
            },
        ),
        migrations.CreateModel(
            name='MetricThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(default='', max_length=50)),
                ('metric_element', models.CharField(default='', max_length=50)),
                ('metric_clear', models.CharField(default='', max_length=200)),
                ('metric_warning', models.CharField(default='', max_length=200)),
                ('metric_critical', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'rules_threshold',
            },
        ),
        migrations.DeleteModel(
            name='CreateDBInit',
        ),
        migrations.RenameField(
            model_name='metricscpu',
            old_name='cpu_guest_nicemak_pct',
            new_name='cpu_guest_nice_pct',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_cleared_sw',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_status',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='sent_notification_sw',
        ),
        migrations.AddField(
            model_name='alert',
            name='last_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metricscpu',
            name='error_cnt',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='metricscpu',
            name='error_msg',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='metricsdbping',
            name='error_cnt',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='metricsdbping',
            name='error_msg',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='metricsload',
            name='error_cnt',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='metricsload',
            name='error_msg',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='metricsmountpoint',
            name='error_cnt',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='metricsmountpoint',
            name='error_msg',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='metrics_sw',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='note',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='alert',
            name='start_dttm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_dttm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='eff_dttm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restore',
            name='start_dttm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serveractivity',
            name='start_dttm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='alertdetail',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Alert'),
        ),
    ]
