# Generated by Django 2.1.1 on 2018-11-24 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0008_auto_20181124_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(default='', max_length=2048)),
                ('start_dttm', models.DateTimeField(auto_now_add=True)),
                ('last_dttm', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(default='', max_length=2048)),
                ('note_by', models.CharField(default='', max_length=30)),
                ('note_color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='', max_length=15)),
                ('ticket', models.CharField(default='', max_length=30)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Server')),
            ],
            options={
                'db_table': 'issue',
                'ordering': ['-start_dttm'],
            },
        ),
        migrations.CreateModel(
            name='IssueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Blackout', 'Blackout'), ('Normal', 'Normal'), ('Unknown', 'Unknown')], default='', max_length=15)),
                ('issue_dttm', models.DateTimeField(auto_now_add=True)),
                ('sent_notification_sw', models.BooleanField(default=False)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Issue')),
            ],
            options={
                'db_table': 'issue_detail',
            },
        ),
        migrations.CreateModel(
            name='IssueNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_dttm', models.DateTimeField(auto_now_add=True)),
                ('issue_note', models.CharField(default='', max_length=10000)),
                ('acknowledged_by', models.CharField(default='', max_length=30)),
                ('acknowledged_dttm', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc))),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('application_contact', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.ApplicationContact')),
                ('issue_detail', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.IssueDetail')),
            ],
            options={
                'db_table': 'issue_notification',
            },
        ),
        migrations.RemoveField(
            model_name='alert',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='alertdetail',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='alertnotification',
            name='alert_detail',
        ),
        migrations.RemoveField(
            model_name='alertnotification',
            name='application_contact',
        ),
        migrations.AlterModelTable(
            name='metricthreshold',
            table='metric_threshold',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertDetail',
        ),
        migrations.DeleteModel(
            name='AlertNotification',
        ),
    ]
