# Generated by Django 2.1.1 on 2018-10-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0009_remove_cluster_haproxy_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='read_only_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.ProtectedError, related_name='read_only_port_id', to='dbaas.ServerPorts'),
        ),
    ]
