# Generated by Django 2.1.1 on 2018-10-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0010_auto_20181002_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restore',
            name='backup_type',
        ),
        migrations.AddField(
            model_name='restore',
            name='restore_type',
            field=models.CharField(choices=[('Full', 'Restore Full'), ('DB', 'Restore Database'), ('Table', 'Restore Table')], max_length=10, null=True),
        ),
    ]
