# Generated by Django 2.1.1 on 2018-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0010_auto_20181126_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='note_color',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Blackout', 'Blackout'), ('Normal', 'Normal'), ('Unknown', 'Unknown')], default='', max_length=15),
        ),
    ]
