# Generated by Django 2.1.1 on 2018-11-28 03:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0011_auto_20181126_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsServerPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('db_ping_status', models.CharField(default='', max_length=30)),
                ('db_ping_response_ms', models.IntegerField(default=0)),
                ('error_cnt', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('error_msg', models.CharField(default='', max_length=500)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_serverm_ping',
            },
        ),
    ]
