# Generated by Django 2.1.1 on 2018-10-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0011_auto_20181002_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerPorts',
            new_name='ServerPort',
        ),
        migrations.AlterModelTable(
            name='serverport',
            table='server_port',
        ),
    ]
