# Generated by Django 2.1.1 on 2018-11-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0012_metricsserverping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metricsserverping',
            old_name='db_ping_response_ms',
            new_name='ping_response_ms',
        ),
        migrations.RemoveField(
            model_name='metricsserverping',
            name='db_ping_status',
        ),
        migrations.AddField(
            model_name='metricsserverping',
            name='ping_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Blackout', 'Blackout')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='metricsdbping',
            name='db_ping_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Blackout', 'Blackout')], default='', max_length=30),
        ),
    ]
