# Generated by Django 2.1.1 on 2018-12-03 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0012_auto_20181202_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsload',
            name='load_15min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='metricsload',
            name='load_1min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='metricsload',
            name='load_5min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
