# Generated by Django 2.1.1 on 2018-12-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0013_auto_20181202_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsmountpoint',
            name='allocated_gb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metricsmountpoint',
            name='used_gb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
