# Generated by Django 2.1.1 on 2018-10-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0013_clusternote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusternote',
            options={'ordering': ['created_dttm']},
        ),
    ]
