# Generated by Django 2.1.4 on 2018-12-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0014_auto_20181203_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_clear',
            new_name='metric_clear_value',
        ),
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_critical',
            new_name='metric_critical_value',
        ),
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_warning',
            new_name='metric_warning_value',
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='metric_clear_predicate_type',
            field=models.CharField(choices=[('>=', '>='), ('>', '>'), ('==', '=='), ('<=', '<='), ('<', '<'), ('IN', 'IN'), ('RegEdit', 'RegEdit')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='metric_critical_predicate_type',
            field=models.CharField(choices=[('>=', '>='), ('>', '>'), ('==', '=='), ('<=', '<='), ('<', '<'), ('IN', 'IN'), ('RegEdit', 'RegEdit')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='metric_warning_predicate_type',
            field=models.CharField(choices=[('>=', '>='), ('>', '>'), ('==', '=='), ('<=', '<='), ('<', '<'), ('IN', 'IN'), ('RegEdit', 'RegEdit')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='server_override',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
    ]
