# Generated by Django 2.1.1 on 2018-10-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0015_auto_20181004_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusternote',
            name='note_color',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], max_length=15, null=True),
        ),
    ]
