# Generated by Django 2.1.4 on 2018-12-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0015_auto_20181205_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('CPU', 'CPU'), ('Load', 'Load'), ('MountPoint', 'Mount Point'), ('PingDB', 'Ping DB'), ('PingServer', 'Ping Server')], default='', max_length=15)),
                ('metric_element', models.CharField(default='', max_length=50)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('active_sw', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'metric_check',
            },
        ),
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_clear_predicate_type',
            new_name='clear_predicate_type',
        ),
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_clear_value',
            new_name='clear_value',
        ),
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_critical_predicate_type',
            new_name='critical_predicate_type',
        ),
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_critical_value',
            new_name='critical_value',
        ),
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_warning_predicate_type',
            new_name='warning_predicate_type',
        ),
        migrations.RenameField(
            model_name='metricthreshold',
            old_name='metric_warning_value',
            new_name='warning_value',
        ),
        migrations.RemoveField(
            model_name='metricthreshold',
            name='metric_element',
        ),
        migrations.RemoveField(
            model_name='metricthreshold',
            name='metric_name',
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='active_sw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='metric_check',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dbaas.MetricCheck'),
        ),
    ]
