# Generated by Django 2.1.1 on 2018-10-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0016_auto_20181004_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveractivities',
            name='activity_status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('PendingRestart', 'PendingRestart'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Successful', 'Successful')], max_length=15, null=True),
        ),
    ]
