# Generated by Django 2.1.4 on 2018-12-06 05:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0016_auto_20181205_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricthreshold',
            name='clear_ticks',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='critical_ticks',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='warning_ticks',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='applicationcontact',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Application'),
        ),
        migrations.AlterField(
            model_name='applicationcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Contact'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Cluster'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Application'),
        ),
        migrations.AlterField(
            model_name='clusternote',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Cluster'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
        migrations.AlterField(
            model_name='issuedetail',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Issue'),
        ),
        migrations.AlterField(
            model_name='issuenotification',
            name='issue_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.IssueDetail'),
        ),
        migrations.AlterField(
            model_name='metricscpu',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
        migrations.AlterField(
            model_name='metricsload',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
        migrations.AlterField(
            model_name='metricsmountpoint',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
        migrations.AlterField(
            model_name='metricspingdb',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
        migrations.AlterField(
            model_name='metricspingserver',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='to_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_to_cluster', to='dbaas.Cluster'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='dbaas.Cluster'),
        ),
        migrations.AlterField(
            model_name='serveractivity',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
    ]
