# Generated by Django 2.1.4 on 2018-12-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0017_auto_20181205_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metriccheck',
            name='active_sw',
            field=models.BooleanField(default=True),
        ),
    ]
