# Generated by Django 2.1.1 on 2018-10-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0018_auto_20181004_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveractivities',
            name='start_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serveractivities',
            name='stop_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
