# Generated by Django 2.1.4 on 2018-12-06 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0018_auto_20181206_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricthreshold',
            name='server_override',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
    ]
