# Generated by Django 2.1.4 on 2018-12-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0019_auto_20181206_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricthreshold',
            name='active_sw',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='metricthreshold',
            name='clear_predicate_type',
            field=models.CharField(choices=[('>=', '>='), ('>', '>'), ('==', '=='), ('<=', '<='), ('<', '<'), ('IN', 'IN'), ('RegEdit', 'RegEdit')], default='<', max_length=15),
        ),
        migrations.AlterField(
            model_name='metricthreshold',
            name='critical_predicate_type',
            field=models.CharField(choices=[('>=', '>='), ('>', '>'), ('==', '=='), ('<=', '<='), ('<', '<'), ('IN', 'IN'), ('RegEdit', 'RegEdit')], default='>=', max_length=15),
        ),
        migrations.AlterField(
            model_name='metricthreshold',
            name='server_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server'),
        ),
        migrations.AlterField(
            model_name='metricthreshold',
            name='warning_predicate_type',
            field=models.CharField(choices=[('>=', '>='), ('>', '>'), ('==', '=='), ('<=', '<='), ('<', '<'), ('IN', 'IN'), ('RegEdit', 'RegEdit')], default='>=', max_length=15),
        ),
    ]
