# Generated by Django 2.1.1 on 2018-10-05 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0020_auto_20181004_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveractivities',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Server'),
        ),
    ]
