# Generated by Django 2.1.4 on 2018-12-06 22:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0020_auto_20181206_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dttm', models.DateTimeField(auto_now_add=True)),
                ('last_dttm', models.DateTimeField(auto_now=True)),
                ('closed_sw', models.BooleanField(default=False)),
                ('critical_ticks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('warning_ticks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('normal_ticks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('note', models.CharField(default='', max_length=2048, null=True)),
                ('note_by', models.CharField(default='', max_length=30, null=True)),
                ('ticket', models.CharField(default='', max_length=30, null=True)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('metric_check', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.MetricCheck')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server')),
            ],
            options={
                'db_table': 'issue_tracker',
                'ordering': ['-start_dttm'],
            },
        ),
    ]
