# Generated by Django 2.1.4 on 2018-12-06 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0021_auto_20181206_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='server',
        ),
        migrations.RemoveField(
            model_name='issuedetail',
            name='issue',
        ),
        migrations.RenameField(
            model_name='issuenotification',
            old_name='issue_dttm',
            new_name='notification_dttm',
        ),
        migrations.RenameField(
            model_name='issuenotification',
            old_name='issue_note',
            new_name='notification_note',
        ),
        migrations.RemoveField(
            model_name='issuenotification',
            name='issue_detail',
        ),
        migrations.AddField(
            model_name='issuenotification',
            name='issue_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbaas.IssueTracker'),
        ),
        migrations.AddField(
            model_name='issuenotification',
            name='notification_method',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='issuenotification',
            name='application_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.ProtectedError, to='dbaas.ApplicationContact'),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='IssueDetail',
        ),
    ]
