# Generated by Django 2.1.1 on 2018-10-05 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0021_auto_20181004_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Cluster'),
        ),
        migrations.AlterField(
            model_name='clusternote',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='dbaas.Cluster'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='from_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='restore_from_cluster', to='dbaas.Cluster'),
        ),
    ]
