# Generated by Django 2.1.1 on 2018-10-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0023_auto_20181005_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_type',
            field=models.CharField(choices=[('Full', 'Full'), ('Incr', 'Incremental'), ('Diff', 'Differential')], default='Full', max_length=10),
        ),
        migrations.AlterField(
            model_name='serverport',
            name='port_status',
            field=models.CharField(choices=[('Free', 'Free'), ('Locked', 'Locked'), ('Used', 'Used'), ('Hidden', 'Hidden')], max_length=10, null=True),
        ),
    ]
