# Generated by Django 2.1.1 on 2018-10-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0024_auto_20181005_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_status',
            field=models.CharField(choices=[('Running', 'Running'), ('Failed', 'Failed'), ('Successful', 'Successful')], max_length=15),
        ),
    ]
