# Generated by Django 2.1.1 on 2018-10-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0025_auto_20181005_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['start_dttm']},
        ),
        migrations.AlterField(
            model_name='restore',
            name='restore_status',
            field=models.CharField(choices=[('Running', 'Running'), ('Failed', 'Failed'), ('Successful', 'Successful')], max_length=15),
        ),
    ]
