# Generated by Django 2.1.1 on 2018-10-07 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0026_auto_20181005_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cluster_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='serverport',
            name='port',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
