# Generated by Django 2.1.1 on 2018-09-26 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng2', '0003_auto_20180922_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDBInit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_cpu', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(14)])),
                ('requested_mem_gb', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(64)])),
                ('requested_db_gb', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(102400)])),
            ],
        ),
        migrations.AlterField(
            model_name='poolserver',
            name='data_center',
            field=models.CharField(choices=[('STL', 'Saint Louis'), ('CH', 'Chicago'), ('PA', 'Piscataway')], max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='data_center',
            field=models.CharField(choices=[('STL', 'Saint Louis'), ('CH', 'Chicago'), ('PA', 'Piscataway')], max_length=20),
        ),
    ]
