# Generated by Django 2.1.4 on 2018-12-30 03:17

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbaas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics_Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(editable=False)),
                ('cpu_idle_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cpu_user_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cpu_system_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cpu_iowait_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cpu_irq_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cpu_steal_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cpu_guest_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cpu_guest_nice_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('error_cnt', models.IntegerField(default=0, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('error_msg', models.CharField(default='', max_length=2000)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_cpu',
            },
        ),
        migrations.CreateModel(
            name='Metrics_CpuLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('load_1min', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('load_5min', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('load_15min', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('error_cnt', models.IntegerField(default=0, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('error_msg', models.CharField(default='', max_length=2000)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_cpu_load',
            },
        ),
        migrations.CreateModel(
            name='Metrics_MountPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(editable=False)),
                ('mount_point', models.CharField(default='', max_length=30)),
                ('allocated_gb', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_gb', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_pct', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('error_cnt', models.IntegerField(default=0, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('error_msg', models.CharField(default='', max_length=2000)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_mount_point',
            },
        ),
        migrations.CreateModel(
            name='Metrics_PingDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('ping_db_status', models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Blackout', 'Blackout')], default='', max_length=30)),
                ('ping_db_response_ms', models.IntegerField(default=0)),
                ('error_cnt', models.IntegerField(default=0, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('error_msg', models.CharField(default='', max_length=2000)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_ping_db',
            },
        ),
        migrations.CreateModel(
            name='Metrics_PingServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('ping_status', models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Blackout', 'Blackout')], default='', max_length=30)),
                ('ping_response_ms', models.IntegerField(default=0)),
                ('error_cnt', models.IntegerField(default=0, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('error_msg', models.CharField(default='', max_length=2000)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_ping_server',
            },
        ),
    ]
