# Generated by Django 2.1.4 on 2018-12-30 05:01

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('dbaas', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics_HostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('cpu_count', models.IntegerField(default=0, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('last_reboot', models.DateTimeField(auto_now_add=True)),
                ('ram_gb', models.IntegerField(default=0, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('os_version', models.CharField(default='?', max_length=200)),
                ('db_version', models.CharField(default='?', max_length=200)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbaas.Server')),
            ],
            options={
                'db_table': 'metrics_host_details',
            },
        ),
    ]
