# Generated by Django 2.1.4 on 2018-12-30 21:50

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metrics_hostdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics_hostdetails',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True, validators=[rest_framework.compat.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='metrics_hostdetails',
            name='db_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metrics_hostdetails',
            name='last_reboot',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='metrics_hostdetails',
            name='os_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metrics_hostdetails',
            name='ram_gb',
            field=models.IntegerField(blank=True, null=True, validators=[rest_framework.compat.MinValueValidator(0)]),
        ),
    ]
