# Generated by Django 2.1.4 on 2018-12-31 06:05

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20181230_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics_hostdetails',
            old_name='cpu_count',
            new_name='cpu',
        ),
        migrations.AddField(
            model_name='metrics_hostdetails',
            name='error_cnt',
            field=models.IntegerField(blank=True, null=True, validators=[rest_framework.compat.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='metrics_hostdetails',
            name='error_msg',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='metrics_hostdetails',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metrics_hostdetails',
            name='last_reboot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
