# Generated by Django 2.1.1 on 2018-09-13 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, to='NG.Cluster'),
            preserve_default=False,
        ),
    ]
