# Generated by Django 2.1.1 on 2018-09-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng', '0002_auto_20180922_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='environment',
            field=models.CharField(blank=True, choices=[('SBX', 'Sandbox'), ('DEV', 'Development'), ('QA', 'Quality Assurance'), ('UAT', 'User Acceptance Testing'), ('PRD', 'Production'), ('PPD', 'Post Production')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('Person', 'Person'), ('Distro', 'Email Group Distro'), ('API', 'API Endpoint')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='poolserver',
            name='environment',
            field=models.CharField(blank=True, choices=[('SBX', 'Sandbox'), ('DEV', 'Development'), ('QA', 'Quality Assurance'), ('UAT', 'User Acceptance Testing'), ('PRD', 'Production'), ('PPD', 'Post Production')], max_length=20),
        ),
        migrations.AlterField(
            model_name='poolserver',
            name='status_in_pool',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Locked', 'Locked for Build'), ('Used', 'Used')], max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='node_role',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary Node'), ('SecondarySync', 'Secondary Node - Replication is Synchronous'), ('SecondaryAsync', 'Secondary Node- Replication is Asynchronous'), ('Arbiter', 'Arbiter Node')], max_length=20),
        ),
    ]
