# Generated by Django 2.1.1 on 2018-09-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0002_server_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolserver',
            name='activeSw',
        ),
        migrations.AddField(
            model_name='poolserver',
            name='statusInPool',
            field=models.CharField(choices=[('NULL', ''), ('AVAILABLE', 'Available'), ('LOCKED', 'Locked for Build'), ('USED', 'Used')], default='NULL', max_length=10),
            preserve_default=False,
        ),
    ]
