# Generated by Django 2.1.1 on 2018-09-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0003_auto_20180914_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolserver',
            name='statusInPool',
            field=models.CharField(choices=[('', 'NULL'), ('Available', 'AVAILABLE'), ('Locked for Build', 'LOCKED'), ('Used', 'USED')], max_length=10),
        ),
    ]
