# Generated by Django 2.1.1 on 2018-09-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0004_auto_20180914_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolserver',
            name='dbms',
        ),
        migrations.AddField(
            model_name='poolserver',
            name='dbmsType',
            field=models.CharField(choices=[('', 'NULL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='dbms',
            field=models.CharField(choices=[('', 'NULL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='poolserver',
            name='statusInPool',
            field=models.CharField(choices=[('', 'NULL'), ('Available', 'Available'), ('Locked for Build', 'Locked'), ('Used', 'Used')], max_length=10),
        ),
    ]
