# Generated by Django 2.1.1 on 2018-09-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0005_auto_20180915_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='contactPhone',
        ),
    ]
