# Generated by Django 2.1.1 on 2018-09-17 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0006_auto_20180916_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='dbms',
            new_name='dbmsType',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='requestedCpu',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='requestedDbGigs',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(102400)]),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='requestedMemGigs',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(64)]),
        ),
    ]
