# Generated by Django 2.1.1 on 2018-09-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng', '0006_backup_restore_serveractivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationContactsDetailsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_type', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=15)),
                ('active_sw', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'application_contacts_details_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
