# Generated by Django 2.1.1 on 2018-09-17 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0007_auto_20180916_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='haPort',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
